# database:
#   host: localhost
#   user: user
#   password: pass
#   database: mydatabase
speculative_method: auto_regressive_greedy
base_model:
    base_model_path: TinyLlama/TinyLlama-1.1B-Chat-v1.0
    base_model_name: tinyllama
speculative_model:
    speculative_model_path: TinyLlama/TinyLlama-1.1B-Chat-v1.0
    speculative_model_name: tinyllama
    load_in_8bit: False
    load_in_4bit: False
conv:
    template: xxx
    system_prompt: xxx
    user_message: "1 + 1 + ?"


