# database:
#   host: localhost
#   user: user
#   password: pass
#   database: mydatabase
speculative_method: eagle
base_model:
    base_model_path: lmsys/vicuna-7b-v1.3
    base_model_name: vicuna
    load_in_8bit: False
    load_in_4_bit: False
speculative_model:
    speculative_model_path: yuhuili/EAGLE-Vicuna-7B-v1.3
    speculative_model_name: eagle
conv:
    template: xxx
    system_prompt: xxx
    user_message: "1 + 1 + ?"


